workflows:
  native-android:
    name: Native Android CI/CD (APK + AAB)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - release_key
      vars:
        PACKAGE_NAME: "com.example.passvault"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Run Lint
        script: |
          ./gradlew lint

      - name: Run Unit Tests
        script: |
          ./gradlew testDebugUnitTest

      - name: Build APK (release)
        script: |
          ./gradlew assembleRelease

      - name: Build AAB (release)
        script: |
          ./gradlew bundleRelease
      - name: Check for sensitive files in repo
        script: |
          echo "Verifying sensitive files..."
          SENSITIVE_FILES=("*.keystore" "*.jks" ".env" "google-services.json")
          for pattern in "${SENSITIVE_FILES[@]}"; do
          found=$(find . -name "$pattern")
           if [ ! -z "$found" ]; then
            echo "⚠️ Sensitive file(s) found:"
            echo "$found"
            exit 1
          fi
          done
          echo "✅ No sensitive files found."
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
      - app/build/reports/lint-results-*.html
      - app/build/reports/tests/**/*.html

    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
